### ISSUE TITLE
Refactoring FacebookCrawler

### ISSUE THREAD

**Issue by nuxlear** [nuxlear/military-letter-crawler#11]
## TODO:
- [ ] static 변수 제거
- [ ] 로그인 및 세션 관리
- [ ] group과 page 추상화 및 통합
- [ ] user 별 status 관리

## Specification
```
FacebookFeed:
  id: str
  type: ['page' | 'group']
  name: str
  time: datetime.datetime
  content: str

FacebookCrawler:
  login()
  initialize()
  add_user()
  add_page()
  add_group()
  crawl(username)
  crawl_all()
  _load()
  _save()
  _remove_duplicate()
  _remove_notice()
```
